In [1]:
import numpy as np


In [2]:
#create list or arrauy
a=np.array([1,2,3,4])

In [3]:
a


array([1, 2, 3, 4])

In [4]:
# create a matrix
b= np.array([[1,2], [3,4]])

In [5]:
# shape
print(a.shape , b.shape)

(4,) (2, 2)


In [6]:
# rehsape
c=a.reshape((4,1))

In [7]:
d=a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [8]:
# concatnate
a=np.array([1,2,3])
b=np.array([4,5])
c=np.concatenate((a,b))

In [9]:
a=np.array([1,2,3])
b=np.array([4,5 ,6])
c=a+b
c

array([5, 7, 9])

In [10]:
# Broadcasting
c=np.array([10])
d=a+c

In [11]:
a=np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [12]:
# slice
# عددی که مینویسیم در اخر یکی قبل اون خواهد بود 
b=a[2:7:2]

In [13]:
c=a[a>3]
c

array([4, 5, 6, 7, 8])

In [14]:
max_a=np.max(a)
min_a=np.min(a)
sum_a=np.sum(a)
sum_a
max_a
min_a
f=np.sort(a)
f

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# start, end , size
a=np.random.randint(0,10,(3,4))
a

array([[6, 5, 2, 8],
       [4, 6, 6, 2],
       [2, 7, 3, 6]])

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
# vertical
c=np.vstack((a,b))
# horizental
c=np.hstack((a,b))
c.shape

(6,)

In [17]:
# normalize
mean_a=np.mean(a)
mean_a

np.float64(2.0)

In [18]:
std_a=np.std(a)
std_a

np.float64(0.816496580927726)

In [19]:
norm_a=(a-mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [20]:
np.std(norm_a)

np.float64(0.9999999999999999)